FROM python:3.5.2-alpine

RUN apk add --no-cache --virtual .build-deps \
        g++ musl-dev linux-headers mariadb-dev \
    && pip install uWSGI mysqlclient \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/*
