FROM python:3.5.2-alpine

RUN apk add --no-cache --virtual .build-deps \
    build-base \
    linux-headers \
    mariadb-dev \
    mariadb-client-libs \
    && \
    pip install --no-cache-dir uWSGI mysqlclient && \
    apk del .build-deps && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /root/.cache/pip/*
    echo done.

