FROM python:3.5.2-alpine

RUN apk add --no-cache --virtual .build-deps \
    build-base \
    linux-headers \
    mariadb-dev \
    mariadb-client-libs \
    && \
    pip install uWSGI mysqlclient && \
    apk del .build-deps && rm -rf /var/cache/apk/* && \

