FROM python:3.5.2-alpine

# install deps, backup libmysqlclient.so
RUN apk add --no-cache --virtual .build-deps \
        g++ musl-dev linux-headers mariadb-dev \
    && pip install uWSGI mysqlclient \
    && (cd /usr/lib && tar cvfz /tmp/libmysqlc.tar.gz libmysqlc*so*) \
    && apk del .build-deps && rm -rf /var/cache/apk/* \
    && (cd /usr/lib && tar zxvf /tmp/libmysqlc.tar.gz)

